version: '2'
services:
  weather:
    image: php:7.0-cli
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 weather.php
    volumes:
      - .:/usr/src/weather
    working_dir: /usr/src/weather
